app/mod_api/controllers.py, app/mod_site/controllers.py
=> Fix auth and publish urls

.travis.yml, app/__init__.py, app/config.py, app/mod_api/controllers.py, app/mod_api/models.py, app/mod_site/controllers.py, app/utils/auth.py, requirements.dev.txt, requirements.txt, tests/mod_api/test_controller.py, tests/mod_api/test_models.py, tests/mod_site/test_site.py
=> Increase unit test and set up travis for postgresql

.gitignore, app/mod_api/controllers.py, app/mod_api/models.py, app/templates/index.html, tests/mod_api/test_models.py
=> S3 upload should use different key for each file

app/__init__.py, app/config.py, app/mod_api/controllers.py, s3_event_listener.py, tests/test_basics.py, zappa_deploy.sh, zappa_settings.json
Addresses https://github.com/frictionlessdata/dpr-api/issues/25
=> [dpr-api-25] Fail early if required config not set

app/config.py, app/mod_api/controllers.py, app/mod_api/models.py, app/mod_site/controllers.py, app/utils/__init__.py, app/utils/auth.py, tests/mod_api/test_controller.py, tests/mod_api/test_models.py
=> [DPR-API-41] added finalize end point for metadata

app/mod_api/controllers.py, app/templates/dashboard.html, tests/mod_api/test_controller.py
Storing JWT encoded token in browser localstorage. Also, modified the TestCase for Callback Handling
=> Stroing JWT token in browser localstorage

app/mod_api/controllers.py, app/mod_api/models.py, app/mod_site/controllers.py, app/templates/dashboard.html, app/templates/index.html
Modified Dashboard, Used JWT token for used for login
=> Dashboard Modified

app/mod_site/controllers.py, app/templates/base.html, app/templates/dashboard.html, app/templates/index.html
Modified Dashboard, Added logout
=> Dashboard Modified for stage

app/mod_site/controllers.py, app/static/js/dashboard.js, app/templates/base.html, app/templates/dashboard.html, app/templates/index.html, tests/mod_site/test_site.py
Fixed Logut, Added test case for logout
=> [dashboard][m #58]: Fix Logout

app/mod_api/controllers.py, app/mod_site/controllers.py, app/static/js/app.js, app/static/js/catalog.js, app/static/js/graph.js, app/templates/_snippets.html, tests/mod_api/test_controller.py
- removed extra zappa prefix 
- Added box around text on hover
- Lines don't mass with circles on hover 
- fixed http/https issue with .pngs files
- Includes data proxy fixups:
- included `/r` before resource name
- streaming supported
=> [views][s]: minor visual fix-ups

app/mod_api/controllers.py, app/mod_site/controllers.py, app/templates/dashboard.html
=> [dashboard][s #59]: Fix URL

app/mod_api/controllers.py, app/mod_site/controllers.py, tests/mod_api/test_controller.py
- CSV streaming working
- JSON streaming working.
- tested
=> Data proxy working

tests/mod_api/test_controller.py
End to End test for Publish Flow
=> [publish][m #15]: Publish End-to-End Test

app/mod_api/controllers.py, app/mod_api/models.py, tests/mod_api/test_controller.py, tests/mod_api/test_models.py
=> [publish][ #62 ]: Ingest README from BitStore to MetaStore

tests/mod_api/test_controller.py
Added more mocking components used by the Finialize Method, which fixed the issue.
=> [publish][m #15]: Modified Test Case

requirements.dev.txt, tests/mod_site/test_site.py
Signup Flow End-to-End test. Included DB, Templates Assertion while adding new user.
=> [signup][m #11] Added Signup Test

tests/mod_site/test_site.py
Modified for the functional test
=> [Signup][-m #11] Test Modified

app/static/js/csv.js, app/templates/base.html
this is related to issue [#92](https://github.com/frictionlessdata/dpr-api/issues/92)
=> issue-92 included csv file into app

app/mod_api/controllers.py, app/mod_api/models.py, app/utils/auth.py, app/utils/authorization.py, tests/mod_api/test_controller.py, tests/utils/test_authorization.py
=> [auth #108] User authorization for actions

app/auth/controllers.py, app/package/models.py, requirements.txt, tests/auth/test_controller.py, tests/package/test_controller.py, tests/package/test_models.py
@rufuspollock / @Fak3 please review
=> Pre generated url is not working with md5 hash - fixes #160

.gitignore, app/__init__.py, app/auth/annotations.py, app/auth/authorization.py, app/auth/controllers.py, app/package/controllers.py, app/package/models.py, app/profile/controllers.py, app/profile/models.py, app/site/controllers.py, tests/auth/test_authorization.py, tests/auth/test_controller.py, tests/package/test_controller.py, tests/package/test_models.py, tests/profile/test_controllers.py, tests/profile/test_models.py, tests/site/test_controller.py
Previously all user, publisher and package related model, test was in /app/package directory 
Split /app/package into /app/package and /app/profile 
/app/profile will hold code for publisher, user and /app/package will hold code for data package
=> [L] Implement publisher information api - ref #202

app/__init__.py, requirements.txt
We get ```No 'Access-Control-Allow-Origin' header is present on the requested resource.``` when called from multiple domain. 
Solution: Add CORS in flask app
=> [fix][s]: Added CORS in flask app

app/package/controllers.py, app/search/models.py, tests/package/test_controller.py, tests/package/test_models.py, tests/search/test_models.py, tests/site/test_controller.py
refs: #200 
- Implement Simple like search on descriptor->> title column.
- Fix bug for insert String value to JSON type column.
=> Implement like query for package title

app/site/controllers.py, app/templates/_snippets.html, app/templates/base.html, app/templates/dataset.html, app/templates/index.html, app/templates/publisher.html, tests/site/test_controller.py
- Converted React publisher page
- Added in place search option base on packages titles
- Modified dataset method in snippets.html to work with publisher and package name
refs- #222
=> [MPA][m] React publisher page - convert to mpa 

.gitignore, app/templates/dataset.html
Fixed bundle.js and main.css public path.
=> [fix][s]: Fix static public path for bundle.js and main.css -refs #229

app/search/controllers.py, app/search/models.py, app/site/controllers.py, app/static/css/style.css, app/templates/base.html, app/templates/search.html, tests/search/test_controllers.py, tests/search/test_models.py
ref #200
- Search input in the search page (and make navbar search smaller)
- Search heading: "Search" on search page
- Show query in search input on search page
- Make sure: publisher:core works and publisher:core list work
Added logo as index html  was by default calling `/favicon.ico` and request was going to `/{publisher}` url.
=> Search page improvements 

app/templates/_snippets.html
refs: #236 
Fixed none handling for package readme value.
=> [fix][s]: Fix none handling for readme data for package list view in snippets.html

app/templates/base.html
Make logout button padding to `m-0`
=> [css][s]: Fix logout button padding refs: #239

app/templates/base.html
The search box in navbar was not responding to enter button.
The main reason was the javascript search method that attached to search button.
The form input was required mode. So blank search was not working.
Removed the search button, search function in js and required mode.
Another bug found was while clicking main-logo it supposed to redirect to home page.
But it was redirecting to '#'. Updated the href to '/'
Ref - #261
=> [xs] fix navbar search box

app/templates/base.html
We use gihub for our authentication. It is good to have a github icon in sign in button.
=> [s] add github icon in signin button refs - #268

app/templates/_snippets.html
The fixes this commit will address are
* Remove hard coded file name. The file name was hard coded as `co2-mm-mlo`
* Remove hard coded file type. The file type was hard coded as `csv`.
Resolves - #275
=> [s] fix bugs in data package view page

app/templates/_snippets.html, app/templates/publisher.html
Changed `img` elements' class name with Bootstrap v3 - `img-responsive`
=> Responsive images works now for Bootstrap v3

app/templates/base.html
- new code for http://staging.datapackaged.com/ 
fixes #322
=> Google Analitycs for staging website

app/site/controllers.py, app/site/models.py, tests/site/test_controller.py
- catalog renamed to Packaged
- removed appending the localurl from descriptor
- refactor tests
- fixes #326
=> Improvements for site/models

app/auth/controllers.py, tests/auth/test_controller.py
- error handler for users without Emails
- swagger doc update
- tests for getting all emails from Github.
=> Tests for user Emails

app/__init__.py, app/auth/annotations.py, app/auth/controllers.py, app/auth/models.py, app/package/controllers.py, app/package/models.py, app/profile/controllers.py, app/search/controllers.py, app/search/models.py, app/site/controllers.py, app/utils/__init__.py, tests/auth/test_controller.py, tests/package/test_controller.py, tests/package/test_models.py
- custom error handler replaced with new exception class following the flask exception handling structure http://flask.pocoo.org/docs/0.12/patterns/apierrors/ 
- handlers for 400, 401, 404 and 500 registered at top level with 
- controllers refactored to handle internal server errors without try/catch
- new tests, as previous ones were not full covering all cases
- tests refactored to assert new error messages
- handling errors in controllers if something goes wrong with bitstore
=> Better error handling

app/config.py, app/site/controllers.py, app/templates/index.html, tests/site/test_controller.py
includes
- list of configurable "best" packages in the config.py for examples and core publishers
- route modify to pass list of packages to  templates
- templates modified to display packages
- test
=> Configurable list of packages

app/config.py, app/site/controllers.py, app/templates/index.html
- using list comprehensions and filter. 
- removed logic from templates. 
- better naming for variables
=> Code Tidy-Up

app/static/js/smoothscroll.js, app/templates/_snippets.html, app/templates/base.html, app/templates/dataset.html, app/templates/index.html
Small fixes for UI: 
- link under the title to not have "by"
- Descriptor should be separated from download
- home page link removed
Scrolling down to anchor tags are now smooth - on front and showcase pages
=> UI improvements

app/logic/__init__.py, app/templates/_snippets.html, tests/logic/test_logic.py, tests/site/test_controller.py
- includes small helper function that validates descriptor - tested
- logic updated and test included to check invalid licenses 
refs #355
=> Fix 500 errors caused by templates

app/templates/_snippets.html, app/templates/base.html
* Added js snippet for tracking outbound links
* Added `onclick` events for resource download buttons
=> Tracking for download links

app/auth/jwt.py, tests/auth/test_models.py
=> removed datapackage.json from bitstore url generator 

app/auth/controllers.py, app/templates/base.html
=> login button back on the page
